### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by LEEINSEO-0118** [LEEINSEO-0118/gh-flow-practice#2]
## Tasks

- [x] Print fizz, if i is mulitiple of 3.
- [x] Print buzz, if i is multiple of 5.
- [x] Print fizzubzz, if i is multiple of 15.
- [x] Otherwise, print i itself

## References
